#!/usr/bin/env python3
"""Build app/assets/players.js — the offline player database used by roster
search. Sources, highest priority first:
  1. _maps.json TEAMOF      (the 170 drafted players, 2026 teams, hand-verified)
  2. ADP_2026-08-27.csv     (300 players, 2026 teams, position from posrank)
  3. proj2026_league.json   (2026 projection names)
  4. FF2026_2025_Scored_LeagueRules.csv (753 players, position + 2025 team)
The app refreshes/extends this from ESPN's live team rosters when online.
"""
import csv,json,re,unicodedata,os
FB='/home/claude/fb'
maps=json.load(open('_maps.json')); BYE=maps['BYE']; TEAMOF=maps['TEAMOF']
def norm(s):
    s=unicodedata.normalize('NFKD',s).lower().replace('.','').replace("'",'').replace('-',' ')
    s=re.sub(r'\b(jr|sr|ii|iii|iv)\b','',s); return re.sub(r'\s+',' ',s).strip()
DEFNAMES={'Pittsburgh Steelers':'PIT','Baltimore Ravens':'BAL','Seattle Seahawks':'SEA',
 'Houston Texans':'HOU','Philadelphia Eagles':'PHI','Cleveland Browns':'CLE',
 'New England Patriots':'NE','Denver Broncos':'DEN','Los Angeles Rams':'LAR',
 'Minnesota Vikings':'MIN'}
db={}   # norm -> {n,p,t}
def put(name,pos,team,prio):
    k=norm(name)
    if not k: return
    cur=db.get(k)
    if cur and cur['_prio']<=prio: 
        if not cur.get('t') and team: cur['t']=team
        if not cur.get('p') and pos: cur['p']=pos
        return
    db[k]={'n':name,'p':pos or (cur or {}).get('p',''),
           't':team or (cur or {}).get('t',''),'_prio':prio}

# 4. 2025 scored file: positions are authoritative, teams are a year old
p=os.path.join(FB,'FF2026_2025_Scored_LeagueRules.csv')
if os.path.exists(p):
    for r in csv.DictReader(open(p)):
        pos=r['pos']
        put(r['name'],pos,r['team'],4)
# 3. projection names (position unknown here, skip if new)
# 2. ADP: 2026 teams + position from posrank
p=os.path.join(FB,'ADP_2026-08-27.csv')
if os.path.exists(p):
    for r in csv.DictReader(open(p)):
        m=re.match(r'([A-Z]+)\d+',r.get('posrank',''))
        pos=m.group(1) if m else ''
        if pos=='DST': pos='DEF'
        put(r['name'],pos,r['team'],2)
# 1. the drafted 170 — most trustworthy team data we have
seed=json.load(open('app/assets/seed.json'))
for t in seed['teams']:
    for pl in t['players']:
        put(pl['name'],pl['pos'],pl['nfl'],1)
# every NFL D/ST as a pickable entry
FULL={'ARI':'Arizona Cardinals','ATL':'Atlanta Falcons','BAL':'Baltimore Ravens','BUF':'Buffalo Bills',
'CAR':'Carolina Panthers','CHI':'Chicago Bears','CIN':'Cincinnati Bengals','CLE':'Cleveland Browns',
'DAL':'Dallas Cowboys','DEN':'Denver Broncos','DET':'Detroit Lions','GB':'Green Bay Packers',
'HOU':'Houston Texans','IND':'Indianapolis Colts','JAX':'Jacksonville Jaguars','KC':'Kansas City Chiefs',
'LAC':'Los Angeles Chargers','LAR':'Los Angeles Rams','LV':'Las Vegas Raiders','MIA':'Miami Dolphins',
'MIN':'Minnesota Vikings','NE':'New England Patriots','NO':'New Orleans Saints','NYG':'New York Giants',
'NYJ':'New York Jets','PHI':'Philadelphia Eagles','PIT':'Pittsburgh Steelers','SEA':'Seattle Seahawks',
'SF':'San Francisco 49ers','TB':'Tampa Bay Buccaneers','TEN':'Tennessee Titans','WAS':'Washington Commanders'}
for ab,nm in FULL.items(): put(nm,'DEF',ab,0)

out=[]
for k,v in db.items():
    if not v['p']: continue
    if v['p'] not in ('QB','RB','WR','TE','K','DEF'): continue
    out.append({'n':v['n'],'p':v['p'],'t':v['t'],'b':BYE.get(v['t'],0)})
out.sort(key=lambda x:(x['p'],x['n']))
with open('app/assets/players.js','w') as f:
    f.write('/* generated by tools/mkplayers.py - offline player database */\n')
    f.write('window.PLAYERDB = ')
    json.dump({'version':'bundled-2026-09-01','count':len(out),'players':out},f,separators=(',',':'))
    f.write(';\n')
import collections
print('players:',len(out),dict(collections.Counter(x['p'] for x in out)))
print('with team:',sum(1 for x in out if x['t']))
