#!/usr/bin/env python3
"""Generate app/assets/seed.json from data_rosters.json + _maps.json.
Re-runnable and idempotent. Ladder step 1."""
import json,re
import unicodedata
maps=json.load(open('_maps.json')); BYE=maps['BYE']; TEAMOF=maps['TEAMOF']
PROJ=json.load(open('proj2026_league.json'))
def _n(x):
    x=unicodedata.normalize('NFKD',x).lower().replace('.','').replace("'",'').replace('-',' ')
    x=re.sub(r'\b(jr|sr|ii|iii|iv)\b','',x); return re.sub(r'\s+',' ',x).strip()
rost=json.load(open('data_rosters.json'))
FLEXPOS={'Carnell Tate':'WR','Ladd McConkey':'WR',"Wan'Dale Robinson":'WR','Jadarian Price':'RB',
 'David Montgomery':'RB','Brian Thomas Jr.':'WR','Jordan Addison':'WR','Christian Watson':'WR',
 'TreVeyon Henderson':'RB','Chuba Hubbard':'RB'}
DEFNAME={'Pittsburgh Steelers':'PIT','Baltimore Ravens':'BAL','Seattle Seahawks':'SEA','Houston Texans':'HOU',
 'Philadelphia Eagles':'PHI','Cleveland Browns':'CLE','New England Patriots':'NE','Denver Broncos':'DEN',
 'Los Angeles Rams':'LAR','Minnesota Vikings':'MIN'}
teams=[];pid=0
for name,v in rost.items():
    players=[]
    for grp in ('S','B'):
        for slot,pname in v[grp]:
            if pname in DEFNAME: pos,nfl='DEF',DEFNAME[pname]
            elif slot=='FLEX':  pos,nfl=FLEXPOS[pname],TEAMOF.get(pname,'')
            else:               pos,nfl=slot,TEAMOF.get(pname,'')
            pid+=1
            pr=PROJ.get(_n(pname))
            rec={'id':'p%03d'%pid,'name':pname,'pos':pos,'nfl':nfl,
                 'bye':BYE.get(nfl,0),'drafted':True}
            if pr:
                rec['projSeason']=round(pr['pts'],1)      # league-scored 2026 projection
                rec['projPG']=round(pr['pts']/17.0,2)     # per game, the advice prior
                rec['projSrc']=('%d source%s'%(pr['nsrc'],'' if pr['nsrc']==1 else 's')) if pr['nsrc'] else 'ADP curve (no source)'
            players.append(rec)
    tid=re.sub(r'[^a-z0-9]','',name.lower())[:12]
    teams.append({'id':tid,'name':name,'owner':name,'players':players})
seed={
 'schema':1,
 'league':{
   'name':'2026 League','season':2026,'teamCount':10,
   'regularSeasonWeeks':14,'playoffWeeks':[15,16,17],
   'slots':['QB','RB','RB','WR','WR','WR','TE','FLEX','K','DEF'],
   'flexEligible':['RB','WR','TE'],
   'rosterSize':17,
   'me':'myteam'
 },
 'byes':BYE,
 'teams':teams
}
json.dump(seed,open('app/assets/seed.json','w'),indent=1)
# seed.js is what the APP loads. A file:// page cannot XHR a sibling file on
# Android WebView (allow-file-access-from-file-urls is off by default), so the
# data ships as a plain <script> instead. seed.json stays for the tools.
with open('app/assets/seed.js','w') as f:
    f.write('/* generated by tools/mkseed.py - do not edit */\n')
    f.write('window.SEED = ')
    json.dump(seed,f,separators=(',',':'))
    f.write(';\n')
n=sum(len(t['players']) for t in teams)
print('teams',len(teams),'players',n)
assert n==170, n
assert all(len(t['players'])==17 for t in teams)
bad=[p['name'] for t in teams for p in t['players'] if not p['nfl'] and p['name']!='Odell Beckham Jr.']
assert not bad, bad
me=[t for t in teams if t['id']=='myteam']
assert me, [t['id'] for t in teams]
withproj=sum(1 for t in teams for p in t['players'] if 'projPG' in p)
print('OK  all 17-man, all mapped, me =',me[0]['name'])
print('OK  preseason projections attached to %d of 170'%withproj)
assert withproj>=165, withproj
